### ISSUE TITLE
ioBroker.pi-hole - Keine Verbindung zu pi-hole bei aktiviertem SSL Zertifikat

### ISSUE THREAD

**Issue by darkiop** [unltdnetworx/ioBroker.pi-hole#1]
Bei aktiviertem SSL-Zertifikiat auf pi-hole kann vom Adapter keine Verbindung zum pi-hole aufgebaut werden. Siehe Screen. Mehr Logs lassen sich leider auch im Debug-Modus des Adapters nicht raus locken.

![grafik](https://user-images.githubusercontent.com/205119/59620605-8b694a80-912d-11e9-9116-f471835b38ea.png)

**Comment by unltdnetworx** [comment]
Das reicht mir schon an Info.
Die Frage ist nur, nutzt du ein selbst-signiertes Zertifikat oder ein gültiges, z.B. Let'sEncrypt?

**Comment by darkiop** [comment]
Let'sEncrypt über DSM / Synology

**Comment by darkiop** [comment]
Falls das was gefixt hast, teste es gerne hier direkt Github.

**Comment by unltdnetworx** [comment]
Verwendest du eine IP oder den Hostnamen?

**Comment by unltdnetworx** [comment]
Ich habe soeben eine Version 1.1.0 zum Testen gepusht. Ein erster Versuch, da ich keine SSL-Verbindung bei mir nutze und es somit nicht testen kann.

**Comment by darkiop** [comment]
Hi,
ich nutze einen lokalen DNS - habe also auch für den pi-hole Container einen hostname im lokalen Netz.

Die 1.1.0 habe ich installiert, der bekannte Fehler mit hostname in der Adapterconfig (https aktiv):

![image](https://user-images.githubusercontent.com/205119/60044586-fc2adc80-96c2-11e9-8103-1f93290a219c.png)

Und hier passend dazu mit IP:

![image](https://user-images.githubusercontent.com/205119/60044617-0c42bc00-96c3-11e9-96cf-bd488c2d42c0.png)

**Comment by darkiop** [comment]
Mit der aktuellen direkt aus dem Master installierten Version funktioniert es.
