### ISSUE TITLE
Problem with Thousands Sign

### ISSUE THREAD

**Issue by jack-blackson** [unltdnetworx/ioBroker.pi-hole#10]
I just started using your adapter, and wanted to save some data in the history adapter for using it in flot.

There I came up with the issue that the numbers are saved incorrectly (at least what I think) in the objects. My iobroker is set up to have "," as a decimal sign. But the adapter saves a value of 2.033 (2 thousand and thirty three) as "2,033" in the object. This means a value of 2. Can you please check? THis is valid for all numbers in the adapter

**Comment by unltdnetworx** [comment]
Confirmed, the type isn't correctly recognized as number but as string. Will fix this.

**Comment by unltdnetworx** [comment]
Should be fixed. Please update over github, delete all datapoints inside objects and restart the adapter.

Please close the issue if the problem is solved.

**Comment by jack-blackson** [comment]
Works great - thanks for the very fast fix!
