### ISSUE TITLE
Problem with the table export

### ISSUE THREAD

**Issue by jack-blackson** [unltdnetworx/ioBroker.pi-hole#11]
Hey!

I tried to use the tables to visualise the biggest requesters, but it seems that there is something strange with the format of the JSON table. 

I created an entry in the forum for that - please contact me for more details:
https://www.forum.iobroker.net/topic/30624/vis-f%C3%BCr-pi-hole-problem-mit-json-tabellen

**Comment by jack-blackson** [comment]
It is in german - please tell me when you need a translation

**Comment by unltdnetworx** [comment]
This not a bug. The data comes from the device in this structure. You can convert it yourself to html.
