### ISSUE TITLE
Numbers shown in States are strings

### ISSUE THREAD

**Issue by FlexerJR** [unltdnetworx/ioBroker.pi-hole#12]
Hello dear developer,

thanks for your great work. I recognized, that numbers shown in states are in string format. 

Due to this reason it is not possible to visualize numbers in Grafana. 

It would be nice to have all numbers as numbers. 

Best regards

**Comment by unltdnetworx** [comment]
Hello FlexerJR,
this problem is already fixed with Issue #11 
Please update the adapter over Github and delete all datapoints in the object area.
