### ISSUE TITLE
Error: connect EHOSTUNREACH

### ISSUE THREAD

**Issue by PapaSpik3** [unltdnetworx/ioBroker.pi-hole#13]
Hello all,

I have the problem, that I couldn't reach my piHole instance. ioBroker and piHole running on the same client in a docker container.

piHole is reachable on port 80 (http) with my browser. In ioBroker I insert my token from PiHole but in the log all the time I get an error:

(796) Error: connect EHOSTUNREACH 192.168.2.10:80

Does the API need more then Port 80 on piHole side or some Port on the ioBroker side?

Thanks a lot! If you need more informations for analysis let me know :)
best regards

**Comment by unltdnetworx** [comment]
Are you running both apps ioBroker and pihole in the same container? Best practice is to separate each service into a single container. You don't have to specify the port if it is the port 80.
Maybe, in your case you should try to give it the internal port.
