### ISSUE TITLE
Error by adding the pihole to iobroker

### ISSUE THREAD

**Issue by SmartyML** [unltdnetworx/ioBroker.pi-hole#19]
Hello,

I set up all correctly like the introduction.
But I get the follow error and no connection:

`error | (13596) Error: getaddrinfo ENOTFOUND http http:80`

**Comment by unltdnetworx** [comment]
Please post a screenshot of your instance settings. The pi-hole web interface is reachable with this ip/hostname?

**Comment by SmartyML** [comment]
There was a failure in my IP adress =) I close the issue
