### ISSUE TITLE
Version 2.0: Status als Boolean für Visu

### ISSUE THREAD

**Issue by pinguin21** [unltdnetworx/ioBroker.pi-hole#2]
Wenn man den Status (zusätzlich) als Boolean Wert zur Verfügung stellen würde, ware er einfacher für Abfragen wie z.B. in Vis zu verwenden.
[https://forum.iobroker.net/topic/22715/aufruf-neuer-adapter-iobroker-pi-hole/66](url)

**Comment by unltdnetworx** [comment]
Wie bereits im Forum erwähnt, soll mit der neuen API alles besser werden. Dann ab Version 2.0 des Adapters und sobald die API stable ist.

Danke für den Feature-Request.

**Comment by AlexanderSch90** [comment]
Wollte ich auch gerade schreiben... Ein "Aus-Ein-Knopf" wäre schon nett. Danke!

**Comment by unltdnetworx** [comment]
Einen Ein-/Aus-Knopf gibt es schon. Zumindest so ähnlich. Man schaltet den Filter mit einer Zeitangabe in Sekunden aus, mit der Eingabe 0 auch dauerhaft.
Bei dem Request geht es um eine reine Statusanzeige.

**Comment by unltdnetworx** [comment]
> 
> 
> Wenn man den Status (zusätzlich) als Boolean Wert zur Verfügung stellen würde, ware er einfacher für Abfragen wie z.B. in Vis zu verwenden.
> [https://forum.iobroker.net/topic/22715/aufruf-neuer-adapter-iobroker-pi-hole/66](url)

Ich habe das in meiner VIS so gelöst, dass ich die beiden Punkte zum aktivieren und deaktivieren als Button bzw. Texteingabe für die Sekunden übereinander gelegt habe und mittels des Bereiches Sichtbarkeit den Datenpunkt "pi-hole.0.summary.status" auf "==" und Wert "enabled" prüfen. Den Button zum Aktivieren setze ich dann auf "verbergen" und das Textfeld auf "anzeigen".

Löst das dein Problem? Ein einziger Ein/Aus-Button ist ja nicht möglich, da das Ausschalten über die Eingabe 0 dauerhaft oder in Sekunden angeben werden muss? Wenn ja, dann bitte den issue schließen.
