### ISSUE TITLE
State updatePiholeAvailable is not updated

### ISSUE THREAD

**Issue by ToTXR4Y** [unltdnetworx/ioBroker.pi-hole#22]
The state "updatePiholeAvailable" is not updated, it is always false (i am using PiHole v5)

It should update if one of the following states is set to true:
- versions/FTL_update
- versions/core_update
- versions/web_update

**Comment by unltdnetworx** [comment]
Unfortunatly this is not an error, because this datapoint was removed with on of the last updates, according to the three update-datapoints you named.
Would suggest to add a new datapoint yourself or add a feature-request for that.
