### ISSUE TITLE
Version 1.3.1 needs update

### ISSUE THREAD

**Issue by jolu1705** [unltdnetworx/ioBroker.pi-hole#24]
**Describe the bug**  
The pi-hole Adapter is missing datapoints for future version and is creating log warn messages

**To Reproduce**  
Install v 1.3.1 and monitor log

**Expected behavior**  
create update containing missing objects

**Screenshots & Logfiles**  
`pi-hole Adapter v 1.3.1 needs an Update:

```
pi-hole.0	2021-04-03 11:00:58.941	warn	(1824) State "pi-hole.0.summary.gravity_last_updated.relative.minutes" has no existing object, this might lead to an error in future versions
pi-hole.0	2021-04-03 11:00:58.940	warn	(1824) State "pi-hole.0.summary.gravity_last_updated.relative.hours" has no existing object, this might lead to an error in future versions
pi-hole.0	2021-04-03 11:00:58.939	warn	(1824) State "pi-hole.0.summary.gravity_last_updated.relative.days" has no existing object, this might lead to an error in future versions
pi-hole.0	2021-04-03 11:00:58.939	warn	(1824) State "pi-hole.0.summary.gravity_last_updated.absolute" has no existing object, this might lead to an error in future versions
pi-hole.0	2021-04-03 11:00:58.938	warn	(1824) State "pi-hole.0.summary.gravity_last_updated.file_exists" has no existing object, this might lead to an error in future versions
pi-hole.0	2021-04-03 11:00:58.937	warn	(1824) State "pi-hole.0.summary.status" has no existing object, this might lead to an error in future versions
pi-hole.0	2021-04-03 11:00:58.937	warn	(1824) State "pi-hole.0.summary.privacy_level" has no existing object, this might lead to an error in future versions
pi-hole.0	2021-04-03 11:00:58.936	warn	(1824) State "pi-hole.0.summary.reply_IP" has no existing object, this might lead to an error in future versions
pi-hole.0	2021-04-03 11:00:58.935	warn	(1824) State "pi-hole.0.summary.reply_CNAME" has no existing object, this might lead to an error in future versions
pi-hole.0	2021-04-03 11:00:58.934	warn	(1824) State "pi-hole.0.summary.reply_NXDOMAIN" has no existing object, this might lead to an error in future versions
pi-hole.0	2021-04-03 11:00:58.933	warn	(1824) State "pi-hole.0.summary.reply_NODATA" has no existing object, this might lead to an error in future versions
pi-hole.0	2021-04-03 11:00:58.932	warn	(1824) State "pi-hole.0.summary.dns_queries_all_types" has no existing object, this might lead to an error in future versions
pi-hole.0	2021-04-03 11:00:58.931	warn	(1824) State "pi-hole.0.summary.unique_clients" has no existing object, this might lead to an error in future versions
pi-hole.0	2021-04-03 11:00:58.929	warn	(1824) State "pi-hole.0.summary.clients_ever_seen" has no existing object, this might lead to an error in future versions
pi-hole.0	2021-04-03 11:00:58.929	warn	(1824) State "pi-hole.0.summary.queries_cached" has no existing object, this might lead to an error in future versions
```
`

**Versions:**  
 - Adapter version: 1.3.1
 - JS-Controller version: 3.2.16
 - Node version: 14.16
 - Operating system: raspbian buster

**Comment by unltdnetworx** [comment]
Please delete all objects and wait or restart the adapter. They will be created new.

Seem to be objects from a former version, which where deleted a few versions ago, because of other new datapoints.

**Comment by jolu1705** [comment]
I stopped the Adapter and deleted all objects. I restarted the adapter and new objects are created but the error is still in the logfile

**Comment by unltdnetworx** [comment]
This is strange. I updated my pihole installation and reinstalled the adapter a few minutes ago. No problems.

Does your objects have values? For example the datapoint pi-hole.0.summary.gravity_last_updated.relative.days? This one shows 0 at my point, because I updated my instance right now.

**Comment by jolu1705** [comment]
pi-hole.0.summary.gravity_last_updated.relative.days has data value "0"

In the meantime I have re-installed my iobroker a several times and 3 days ago I switched to a totally new hardware platform also. I will monitor the situation and check if the error comes up again. If not it was a buggy installation, if yes I will report here again. 

Thanks for your fast response.

**Comment by unltdnetworx** [comment]
Please test the new version via github-installation
