### ISSUE TITLE
Diverse Warnungen seit js-controller Update auf 3.3

### ISSUE THREAD

**Issue by Azathoth88** [unltdnetworx/ioBroker.pi-hole#25]
Seit dem Update der js-controller auf 3.3 erhalte ich im Sekundentakt etliche Warnungen:

State value to set for "pi-hole.0.topItems.top_queries.data-table" has wrong type "string" but has to be "object"
pi-hole.0 | 2021-04-30 08:58:14.290 | warn | State value to set for "pi-hole.0.topItems.top_queries.data-table" has wrong type "string" but has to be "object"
pi-hole.0 | 2021-04-30 08:58:14.290 | warn | State value to set for "pi-hole.0.topItems.top_queries.data-table" has wrong type "string" but has to be "object"
pi-hole.0 | 2021-04-30 08:58:14.290 | warn | State value to set for "pi-hole.0.topItems.top_queries.data-table" has wrong type "string" but has to be "object"
pi-hole.0 | 2021-04-30 08:58:14.286 | warn | State value to set for "pi-hole.0.topItems.top_queries.data-table" has wrong type "string" but has to be "object"
pi-hole.0 | 2021-04-30 08:58:14.286 | warn | State value to set for "pi-hole.0.topItems.top_queries.data-table" has wrong type "string" but has to be "object"
pi-hole.0 | 2021-04-30 08:58:14.286 | warn | State value to set for "pi-hole.0.topItems.top_queries.data-table" has wrong type "string" but has to be "object"
pi-hole.0 | 2021-04-30 08:58:14.285 | warn | State value to set for "pi-hole.0.topItems.top_queries.data-table" has wrong type "string" but has to be "object"
pi-hole.0 | 2021-04-30 08:58:14.285 | warn | State value to set for "pi-hole.0.summaryRaw.gravity_last_updated.relative.minutes" has wrong type "number" but has to be "string"
pi-hole.0 | 2021-04-30 08:58:14.285 | warn | State value to set for "pi-hole.0.summaryRaw.gravity_last_updated.relative.hours" has wrong type "number" but has to be "string"
pi-hole.0 | 2021-04-30 08:58:14.285 | warn | State value to set for "pi-hole.0.summaryRaw.gravity_last_updated.relative.days" has wrong type "number" but has to be "string"
pi-hole.0 | 2021-04-30 08:58:14.284 | warn | State value to set for "pi-hole.0.overTimeData10mins.ads_over_time.data-table" has wrong type "string" but has to be "object"
pi-hole.0 | 2021-04-30 08:58:14.284 | warn | State value to set for "pi-hole.0.overTimeData10mins.ads_over_time.data-table" has wrong type "string" but has to be "object"
pi-hole.0 | 2021-04-30 08:58:14.284 | warn | State value to set for "pi-hole.0.overTimeData10mins.ads_over_time.data-table" has wrong type "string" but has to be "object"
pi-hole.0 | 2021-04-30 08:58:14.284 | warn | State value to set for "pi-hole.0.overTimeData10mins.ads_over_time.data-table" has wrong type "string" but has to be "object"
pi-hole.0 | 2021-04-30 08:58:14.284 | warn | State value to set for "pi-hole.0.overTimeData10mins.ads_over_time.data-table" has wrong type "string" but has to be "object"
pi-hole.0 | 2021-04-30 08:58:14.284 | warn | State value to set for "pi-hole.0.overTimeData10mins.ads_over_time.data-table" has wrong type "string" but has to be "object"
pi-hole.0 | 2021-04-30 08:58:14.283 | warn | State value to set for "pi-hole.0.overTimeData10mins.ads_over_time.data-table" has wrong type "string" but has to be "object"

**Comment by unltdnetworx** [comment]
Ein paar der Meldungen sollten jetzt weg sein. Bitte mal über die Guthub-Katze updaten.

**Comment by OberfragGER** [comment]
> Ein paar der Meldungen sollten jetzt weg sein. Bitte mal über die Guthub-Katze updaten.

Ich hab jetzt auf auch 3.3 geupdatet und auch ohne ende infos:
Danach nochmal über die Katze installiert (installiert Version war 1.3.2 und ist jetzt auch 1.3.2)
Ideen?
<html>
<body>


pi-hole.0 | 2021-08-10 21:52:28.829 | info | State value to set for "pi-hole.0.summary.gravity_last_updated.relative.minutes" has to be type "text" but received type "number"
-- | -- | -- | --
pi-hole.0 | 2021-08-10 21:52:28.829 | info | State value to set for "pi-hole.0.summary.gravity_last_updated.relative.hours" has to be type "text" but received type "number"
pi-hole.0 | 2021-08-10 21:52:28.828 | info | State value to set for "pi-hole.0.summary.gravity_last_updated.relative.days" has to be type "text" but received type "number"
pi-hole.0 | 2021-08-10 21:52:28.828 | info | State value to set for "pi-hole.0.summary.gravity_last_updated.absolute" has to be type "value" but received type "number"
pi-hole.0 | 2021-08-10 21:52:28.827 | info | State value to set for "pi-hole.0.summary.gravity_last_updated.file_exists" has to be type "indicator.working" but received type "boolean"
pi-hole.0 | 2021-08-10 21:52:28.827 | info | State value to set for "pi-hole.0.summary.status" has to be type "text" but received type "string"
pi-hole.0 | 2021-08-10 21:52:28.827 | info | State value to set for "pi-hole.0.summary.privacy_level" has to be type "text" but received type "number"
pi-hole.0 | 2021-08-10 21:52:28.826 | info | State value to set for "pi-hole.0.summary.reply_IP" has to be type "text" but received type "number"
pi-hole.0 | 2021-08-10 21:52:28.826 | info | State value to set for "pi-hole.0.summary.reply_CNAME" has to be type "text" but received type "number"
pi-hole.0 | 2021-08-10 21:52:28.825 | info | State value to set for "pi-hole.0.summary.reply_NXDOMAIN" has to be type "text" but received type "number"
pi-hole.0 | 2021-08-10 21:52:28.825 | info | State value to set for "pi-hole.0.summary.reply_NODATA" has to be type "text" but received type "number"
pi-hole.0 | 2021-08-10 21:52:28.824 | info | State value to set for "pi-hole.0.summary.dns_queries_all_types" has to be type "text" but received type "number"
pi-hole.0 | 2021-08-10 21:52:28.824 | info | State value to set for "pi-hole.0.summary.unique_clients" has to be type "text" but received type "number"
pi-hole.0 | 2021-08-10 21:52:28.823 | info | State value to set for "pi-hole.0.summary.clients_ever_seen" has to be type "text" but received type "number"
pi-hole.0 | 2021-08-10 21:52:28.823 | info | State value to set for "pi-hole.0.summary.queries_cached" has to be type "text" but received type "number"
pi-hole.0 | 2021-08-10 21:52:28.823 | info | State value to set for "pi-hole.0.summary.queries_forwarded" has to be type "text" but received type "number"
pi-hole.0 | 2021-08-10 21:52:28.822 | info | State value to set for "pi-hole.0.summary.unique_domains" has to be type "text" but received type "number"
pi-hole.0 | 2021-08-10 21:52:28.822 | info | State value to set for "pi-hole.0.summary.ads_percentage_today" has to be type "text" but received type "number"
pi-hole.0 | 2021-08-10 21:52:28.821 | info | State value to set for "pi-hole.0.summary.ads_blocked_today" has to be type "text" but received type "number"
pi-hole.0 | 2021-08-10 21:52:28.821 | info | State value to set for "pi-hole.0.summary.dns_queries_today" has to be type "text" but received type "number"
pi-hole.0 | 2021-08-10 21:52:28.820 | info | State value to set for "pi-hole.0.summary.domains_being_blocked" has to be type "text" but received type "number"
pi-hole.0 | 2021-08-10 21:52:28.681 | info | State value to set for "pi-hole.0.summaryRaw.gravity_last_updated.relative.minutes" has to be type "text" but received type "number"
pi-hole.0 | 2021-08-10 21:52:28.681 | info | State value to set for "pi-hole.0.summaryRaw.gravity_last_updated.relative.hours" has to be type "text" but received type "number"
pi-hole.0 | 2021-08-10 21:52:28.680 | info | State value to set for "pi-hole.0.summaryRaw.gravity_last_updated.relative.days" has to be type "text" but received type "number"
pi-hole.0 | 2021-08-10 21:52:28.680 | info | State value to set for "pi-hole.0.summaryRaw.gravity_last_updated.absolute" has to be type "value" but received type "number"
pi-hole.0 | 2021-08-10 21:52:28.680 | info | State value to set for "pi-hole.0.summaryRaw.gravity_last_updated.file_exists" has to be type "indicator.working" but received type "boolean"
pi-hole.0 | 2021-08-10 21:52:28.679 | info | State value to set for "pi-hole.0.summaryRaw.status" has to be type "boolean" but received type "string"
pi-hole.0 | 2021-08-10 21:52:28.625 | info | State value to set for "pi-hole.0.summaryRaw.privacy_level" has to be type "value" but received type "number"
pi-hole.0 | 2021-08-10 21:52:28.624 | info | State value to set for "pi-hole.0.summaryRaw.reply_IP" has to be type "value" but received type "number"
pi-hole.0 | 2021-08-10 21:52:28.624 | info | State value to set for "pi-hole.0.summaryRaw.reply_CNAME" has to be type "value" but received type "number"
pi-hole.0 | 2021-08-10 21:52:28.623 | info | State value to set for "pi-hole.0.summaryRaw.reply_NXDOMAIN" has to be type "value" but received type "number"
pi-hole.0 | 2021-08-10 21:52:28.623 | info | State value to set for "pi-hole.0.summaryRaw.reply_NODATA" has to be type "value" but received type "number"
pi-hole.0 | 2021-08-10 21:52:28.622 | info | State value to set for "pi-hole.0.summaryRaw.dns_queries_all_types" has to be type "value" but received type "number"
pi-hole.0 | 2021-08-10 21:52:28.622 | info | State value to set for "pi-hole.0.summaryRaw.unique_clients" has to be type "value" but received type "number"
pi-hole.0 | 2021-08-10 21:52:28.621 | info | State value to set for "pi-hole.0.summaryRaw.clients_ever_seen" has to be type "value" but received type "number"
pi-hole.0 | 2021-08-10 21:52:28.621 | info | State value to set for "pi-hole.0.summaryRaw.queries_cached" has to be type "value" but received type "number"
pi-hole.0 | 2021-08-10 21:52:28.621 | info | State value to set for "pi-hole.0.summaryRaw.queries_forwarded" has to be type "value" but received type "number"
pi-hole.0 | 2021-08-10 21:52:28.620 | info | State value to set for "pi-hole.0.summaryRaw.unique_domains" has to be type "value" but received type "number"
pi-hole.0 | 2021-08-10 21:52:28.620 | info | State value to set for "pi-hole.0.summaryRaw.ads_percentage_today" has to be type "value" but received type "number"
pi-hole.0 | 2021-08-10 21:52:28.619 | info | State value to set for "pi-hole.0.summaryRaw.ads_blocked_today" has to be type "value" but received type "number"
pi-hole.0 | 2021-08-10 21:52:28.619 | info | State value to set for "pi-hole.0.summaryRaw.dns_queries_today" has to be type "value" but received type "number"
pi-hole.0 | 2021-08-10 21:52:28.618 | info | State value to set for "pi-hole.0.summaryRaw.domains_being_blocked" has to be type "value" but received type "number"
pi-hole.0 | 2021-08-10 21:52:28.618 | info | State value to set for "pi-hole.0.type.type" has to be type "text" but received type "string"
pi-hole.0 | 2021-08-10 21:52:28.616 | info | State value to set for "pi-hole.0.version.version" has to be type "value" but received type "number"
pi-hole.0 | 2021-08-10 21:52:28.615 | info | State value to set for "pi-hole.0.getQueryTypes.querytypes.TXT" has to be type "value" but received type "number"
pi-hole.0 | 2021-08-10 21:52:28.614 | info | State value to set for "pi-hole.0.getQueryTypes.querytypes.PTR" has to be type "value" but received type "number"
pi-hole.0 | 2021-08-10 21:52:28.614 | info | State value to set for "pi-hole.0.getQueryTypes.querytypes.SOA" has to be type "value" but received type "number"
pi-hole.0 | 2021-08-10 21:52:28.613 | info | State value to set for "pi-hole.0.getQueryTypes.querytypes.SRV" has to be type "value" but received type "number"
pi-hole.0 | 2021-08-10 21:52:28.613 | info | State value to set for "pi-hole.0.getQueryTypes.querytypes.ANY" has to be type "value" but received type "number"
pi-hole.0 | 2021-08-10 21:52:28.613 | info | State value to set for "pi-hole.0.getQueryTypes.querytypes.AAAA (IPv6)" has to be type "value" but received type "number"
pi-hole.0 | 2021-08-10 21:52:28.612 | info | State value to set for "pi-hole.0.getQueryTypes.querytypes.A (IPv4)" has to be type "value" but received type "number"
pi-hole.0 | 2021-08-10 21:51:28.907 | info | State value to set for "pi-hole.0.summaryRaw.gravity_last_updated.relative.minutes" has to be type "text" but received type "number"
pi-hole.0 | 2021-08-10 21:51:28.907 | info | State value to set for "pi-hole.0.summaryRaw.gravity_last_updated.relative.hours" has to be type "text" but received type "number"
pi-hole.0 | 2021-08-10 21:51:28.907 | info | State value to set for "pi-hole.0.summaryRaw.gravity_last_updated.relative.days" has to be type "text" but received type "number"
pi-hole.0 | 2021-08-10 21:51:28.906 | info | State value to set for "pi-hole.0.summaryRaw.gravity_last_updated.absolute" has to be type "value" but received type "number"
pi-hole.0 | 2021-08-10 21:51:28.906 | info | State value to set for "pi-hole.0.summaryRaw.gravity_last_updated.file_exists" has to be type "indicator.working" but received type "boolean"
pi-hole.0 | 2021-08-10 21:51:28.906 | info | State value to set for "pi-hole.0.summaryRaw.status" has to be type "boolean" but received type "string"
pi-hole.0 | 2021-08-10 21:51:28.906 | info | State value to set for "pi-hole.0.summaryRaw.privacy_level" has to be type "value" but received type "number"
pi-hole.0 | 2021-08-10 21:51:28.905 | info | State value to set for "pi-hole.0.summaryRaw.reply_IP" has to be type "value" but received type "number"
pi-hole.0 | 2021-08-10 21:51:28.905 | info | State value to set for "pi-hole.0.summaryRaw.reply_CNAME" has to be type "value" but received type "number"


</body>
</html>

**Comment by unltdnetworx** [comment]
Bitte mal den Adapter stoppen, alle Datenpunkte des Adapters im Reiter Objekte löschen und den Adapter wieder starten. Die Datenpunkte werden wieder erzeugt.
Falls die Warnungen weiterhin kommen, muss ich manuell nachbessern.

**Comment by OberfragGER** [comment]
> Bitte mal den Adapter stoppen, alle Datenpunkte des Adapters im Reiter Objekte löschen und den Adapter wieder starten. Die Datenpunkte werden wieder erzeugt.
> Falls die Warnungen weiterhin kommen, muss ich manuell nachbessern.

Ähm. Das war mal neu schnelle Antwort. Nice.
Log sieht gut aus. Danke für die Mühe.

**Comment by unltdnetworx** [comment]
Sehr schön :)
