### ISSUE TITLE
Multiple states at getQueryTypes

### ISSUE THREAD

**Issue by spaceduck518** [unltdnetworx/ioBroker.pi-hole#32]
PiHole adapter generates over 14.000 objects at the object tree under getQueryTypes . Almost every object contains a single character Looks like an bug. I reinstalled the adapter but the objects will be generated again. 

**Screenshots & Logfiles**  
![Unbenannt](https://user-images.githubusercontent.com/41075143/140089785-0dafccf6-2ef5-4906-ad90-12028f7efe42.JPG)

**Versions:**  
 - Adapter version: 1.3.2
 - JS-Controller version: 3.3.18
 - Node version: 12.22.7
 - Operating system: Ubuntu Server 20.04 LTS

**Comment by unltdnetworx** [comment]
Sry for the late reply. I'll delete this points this week, as they are not really relevant I think. But the api creates them, so the adapter does.

**Comment by unltdnetworx** [comment]
Please update via github and report if the datapoints are still created.

**Comment by spaceduck518** [comment]
Datapoints are OK now. Guess you can close this issue.
THANKS!
