### ISSUE TITLE
ioBroker crashes when activating instance (pihole and iobroker on same device)

### ISSUE THREAD

**Issue by harryslapalot** [unltdnetworx/ioBroker.pi-hole#33]
I have installed iobroker and pihole on the same device (Docker on Synology).
When I start the instance, iobroker crashes almost instantly (nothing in the logs, iobroker is just not reachable any more).
When I set the adapter up with another IP (another raspberry that runs pihole for tests) everything works fine.
Any ideas how I can fix this?

**Comment by unltdnetworx** [comment]
What result do you get by calling http://yourIPadressOfIobroker/admin/api.php ?

**Comment by harryslapalot** [comment]
Thanks for pointing me in the right direction. I got the login screen of my synology which showed the obvious error.
I tried IP:Portnumber in the adapter and now it works like it should! The Pihole Port was changed from standard to avoid conflicts with the web admin of the synology. Didn't think about it when setting up the adapter.
