### ISSUE TITLE
kann nicht mit dem PiHole Verbinden

### ISSUE THREAD

**Issue by luckyheiko** [unltdnetworx/ioBroker.pi-hole#35]
Hallo 

kann den Adapter nicht mit dem PiHole verbinden und kann leider keinen Fehler sehen.
der IOBroker und das Pihole laufen auf jeweils in einem Docker auf Unraid. 
IO aud 10.3 das Pihole auf 10.2

dennoch bekomme ich bei egal welchen einstellungen die Fehlermeldung 
  | Error: connect EHOSTUNREACH 192.168.10.2:80
wenn ich in meinem Browser die IP manuel eingebe werde ich auf 192.168.10.2/admin weitergeleiter.
Kann es daran liegen?

(API / http, https usw. habe ich alles ausprobiert.

würde mich über einen Tipp sehr freuen

das Pihole läuft ohne Probleme und ist unter der 192.168.10.2 zu erreichen.

vielen dank 
Node.js: v14.18.3
NPM: 6.14.15

**Describe the bug**  

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**

**Comment by luckyheiko** [comment]
<html><body>


pi-hole.0 | 2022-01-29 21:00:42.833 | error | Error: connect EHOSTUNREACH 192.168.10.2:80
-- | -- | -- | --
pi-hole.0 | 2022-01-29 21:00:42.833 | error | Error: connect EHOSTUNREACH 192.168.10.2:80
pi-hole.0 | 2022-01-29 21:00:42.832 | error | Error: connect EHOSTUNREACH 192.168.10.2:80
pi-hole.0 | 2022-01-29 21:00:42.832 | error | Error: connect EHOSTUNREACH 192.168.10.2:80
pi-hole.0 | 2022-01-29 21:00:42.832 | error | Error: connect EHOSTUNREACH 192.168.10.2:80
pi-hole.0 | 2022-01-29 21:00:42.832 | error | Error: connect EHOSTUNREACH 192.168.10.2:80
pi-hole.0 | 2022-01-29 21:00:42.832 | error | Error: connect EHOSTUNREACH 192.168.10.2:80
pi-hole.0 | 2022-01-29 21:00:42.831 | error | Error: connect EHOSTUNREACH 192.168.10.2:80
pi-hole.0 | 2022-01-29 21:00:42.831 | error | Error: connect EHOSTUNREACH 192.168.10.2:80
pi-hole.0 | 2022-01-29 21:00:12.881 | error | Error: connect EHOSTUNREACH 192.168.10.2:80
pi-hole.0 | 2022-01-29 21:00:12.880 | error | Error: connect EHOSTUNREACH 192.168.10.2:80
pi-hole.0 | 2022-01-29 21:00:12.880 | error | Error: connect EHOSTUNREACH 192.168.10.2:80
pi-hole.0 | 2022-01-29 21:00:12.880 | error | Error: connect EHOSTUNREACH 192.168.10.2:80
pi-hole.0 | 2022-01-29 21:00:12.880 | error | Error: connect EHOSTUNREACH 192.168.10.2:80
pi-hole.0 | 2022-01-29 21:00:12.879 | error | Error: connect EHOSTUNREACH 192.168.10.2:80
pi-hole.0 | 2022-01-29 21:00:12.879 | error | Error: connect EHOSTUNREACH 192.168.10.2:80
pi-hole.0 | 2022-01-29 21:00:12.879 | error | Error: connect EHOSTUNREACH 192.168.10.2:80
pi-hole.0 | 2022-01-29 21:00:12.878 | error | Error: connect EHOSTUNREACH 192.168.10.2:80


</body>
</html>

oder liegt das an der schnellen abfrage??

**Comment by unltdnetworx** [comment]
Hat der ioBroker Container auch tatsächlich Zugriff auf den Pihole Container?
Im Adapter ist die IP-Adresse ohne http/https eingetragen?

**Comment by luckyheiko** [comment]
root@d:/opt/iobroker# ping 192.168.10.2
PING 192.168.10.2 (192.168.10.2) 56(84) bytes of data.
From 192.168.10.3 icmp_seq=1 Destination Host Unreachable
From 192.168.10.3 icmp_seq=2 Destination Host Unreachable
From 192.168.10.3 icmp_seq=3 Destination Host Unreachable
From 192.168.10.3 icmp_seq=4 Destination Host Unreachable
From 192.168.10.3 icmp_seq=5 Destination Host Unreachable
From 192.168.10.3 icmp_seq=6 Destination Host Unreachable
From 192.168.10.3 icmp_seq=7 Destination Host Unreachable
From 192.168.10.3 icmp_seq=8 Destination Host Unreachable
From 192.168.10.3 icmp_seq=9 Destination Host Unreachable
From 192.168.10.3 icmp_seq=10 Destination Host Unreachable
From 192.168.10.3 icmp_seq=11 Destination Host Unreachable
From 192.168.10.3 icmp_seq=12 Destination Host Unreachable
^C
--- 192.168.10.2 ping statistics ---
13 packets transmitted, 0 received, +12 errors, 100% packet loss, time 12268ms
pipe 4

ok, jetzt bin ich etwas verwirrt. 
beide Container IO läuft als Host und der Pi mit br0 (eigene IP) sind in meinem Netzwerk.
aber wieso kann der eine den anderen nicht anpingen?

leider habe ich aber auch in der Config, keine möglichkeit den Port 80 nach 'außen' zu legen. 

und soweit ich das sehe, wir nur der 8081 nach außen freigegeben?!
![1](https://user-images.githubusercontent.com/26415601/151689548-be938633-3032-4bd9-bf87-c40f7b943a17.JPG)

**Comment by unltdnetworx** [comment]
Die Port 8081 für den ioBroker ist korrekt, damit ist ja die Weboberfläche erreichbar. Spielt aber für das Problem keine Rolle. Interessant ist der Port des pihole nach außen. Ist der unter 80 oder 443 erreichbar?

**Comment by luckyheiko** [comment]
![grafik](https://user-images.githubusercontent.com/26415601/151690486-d1b25843-cac1-4d79-a2db-8614f75228ab.png)

**Comment by unltdnetworx** [comment]
Der Container ist also über Port 80 von außen erreichbar, aber nicht von ioBroker aus.
Vllt. wäre das eine Frage im ioBroker Forum wert. Die Antwort würde mich auch interessieren, bitte mich im Forum verlinken.
Es liegt somit nicht am pi-hole Adapter.
Falls eine Lösung gefunden wird, bitte auch hier einstellen.

**Comment by luckyheiko** [comment]
das wäre meiner meinung nach aber unlogisch, 
die Shelly (werden ja auch über http abgefragt, funktionieren ja auch. 
Wieso soll es nun am Docker liegen?
![grafik](https://user-images.githubusercontent.com/26415601/151691975-70e85b03-6895-4506-a74b-4e219b43fc36.png)

hier sollte dann ja auch port 80 genommen werden oder?

**Comment by unltdnetworx** [comment]
Bitte mal einen Screenshot der Adapters Einstellungen einfügen.

**Comment by luckyheiko** [comment]
ok, ich bin gerade doch etwas verwirrt.
root@der-ripper:/opt/iobroker# ping 192.168.10.113
PING 192.168.10.113 (192.168.10.113) 56(84) bytes of data.
From 192.168.10.3 icmp_seq=1 Destination Host Unreachable
From 192.168.10.3 icmp_seq=2 Destination Host Unreachable
From 192.168.10.3 icmp_seq=3 Destination Host Unreachable
From 192.168.10.3 icmp_seq=4 Destination Host Unreachable
From 192.168.10.3 icmp_seq=5 Destination Host Unreachable
From 192.168.10.3 icmp_seq=6 Destination Host Unreachable
From 192.168.10.3 icmp_seq=7 Destination Host Unreachable
From 192.168.10.3 icmp_seq=8 Destination Host Unreachable
From 192.168.10.3 icmp_seq=9 Destination Host Unreachable
^C
--- 192.168.10.113 ping statistics ---
12 packets transmitted, 0 received, +9 errors, 100% packet loss, time 11281ms
pipe 4

aber dennoch scheint der Shelly zu Anworten, oder Anworten zu können.


![grafik](https://user-images.githubusercontent.com/26415601/151695412-12b89c7c-b7fe-46aa-9667-d203503448a7.png)

**Comment by unltdnetworx** [comment]
Evtl. werden ICMP Pakete (Ping) nicht durchgelassen. Ist also nicht unbedingt aussagekräftig, ob der ioBroker den Pihole tatsächlich erreichen kann.
Was sagt der Befehl `telnet 192.168.19.2 80` auf der ioBroker Console?

**Comment by luckyheiko** [comment]
root@r:/opt/iobroker# telnet
bash: telnet: command not found

root@r:/opt/iobroker# netstat -an|grep LISTEN|grep :80
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:8083            0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:8086            0.0.0.0:*               LISTEN     
tcp6       0      0 :::80                   :::*                    LISTEN     
tcp6       0      0 :::8081                 :::*                    LISTEN     
tcp6       0      0 :::8082                 :::*                    LISTEN     
tcp6       0      0 :::8083                 :::*                    LISTEN     
tcp6       0      0 :::8086                 :::*                    LISTEN     
root@r:/opt/iobroker# 

kann es sein, das es daran liegt das Unraid(192.168.10.2) auf 80 sein Webinterface hat und deswegen dann der IOBroker durcheinander kommt?

wenn ich das aber richtig deute, schafft das der Shelly irgendwie
root@r:/opt/iobroker# netstat
Active Internet connections (w/o servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 192.168.10.3:55020      192.168.10.114:80       TIME_WAIT

**Comment by unltdnetworx** [comment]
Ich denke, dass es ein Problem der Kommunikation unter den Containern ist. Shelly kann man damit nicht vergleichen, weil das ein externes Gerät ist, genau wie ein Aufruf der Weboberfläche des pihole von einem Rechner aus möglich ist.

Wie sind denn die Containern konfiguriert? Haben alle eine eigene IP-Adresse oder ist einer davon im Host-Modus?

Die Frage ist aber tatsächlich eher in einem Forum, z.B. ioBroker oder unRaid besser aufgehoben.

**Comment by luckyheiko** [comment]
der IOBroker läuft als Host, da er bei mir sonst nicht Steuert. (10.3)
das PiHole, hat ne einge IP (br0) (10.2)

**Comment by Cuthalion75** [comment]
Hallo,

nur als Ergänzung, ich hatte das identische Setup und das gleiche Problem.

Die Lösung für mich war:

Unraid --> Settings --> Docker --> Host access to custom networks: Enabled

Im default ist das auf "disabled"

**Comment by unltdnetworx** [comment]
Danke für die Info.
