### ISSUE TITLE
Wrong types in "versions"

### ISSUE THREAD

**Issue by marc577** [unltdnetworx/ioBroker.pi-hole#39]
Hello,
I recognized that, some values in the versions attribute are not handled correctly and are being initialized as channel. But they from type "string".
These are the values handled wrong in my installation (js-controller 4):
"FTL_branch"
"FTL_latest"
"core_latest"
"web_latest"

**Comment by unltdnetworx** [comment]
Please stop the adapter, delete the datapoints or the whole tree and restart the adapter.
#25 has been a similar problem, I think.
