### ISSUE TITLE
10mins Ads over Time Chart

### ISSUE THREAD

**Issue by Mephisto090** [unltdnetworx/ioBroker.pi-hole#42]
Hej,

wäre es möglich die Tabelle Jarvis "freundlich" zu machen? Jarvis kommt aktuell noch nicht damit klar json als Bar-Chart dazustellen.

VG

**Comment by unltdnetworx** [comment]
Hej,
das geht leider nicht, da die Tabelle direkt von pihole erstellt wird.

Das muss der Nutzer dann leider selbst machen und passt thematisch nicht in den Adapter.
