### ISSUE TITLE
Add port to setting

### ISSUE THREAD

**Issue by joerghohn** [unltdnetworx/ioBroker.pi-hole#43]
Is there a possibility to add the port to the setting?
My pi-hole is not running on standard http port 80 so it would be nice to have the possibility to add the port to the configuration.

**Comment by unltdnetworx** [comment]
Just add the port after the ip separated by :
e.g. 192.168.0.2:80

**Comment by joerghohn** [comment]
Thanks, I tried that before but had a typo in the IP Adress
