### ISSUE TITLE
Updates values in iobroker only on adapter (re)start

### ISSUE THREAD

**Issue by joerghohn** [unltdnetworx/ioBroker.pi-hole#44]
**Describe the bug**  
When I (re)start the adapter, everything seems fine. 
While the adapter is running, no values in iobroker are updated.

**To Reproduce**  
1. (re)start adapter
2. Find Values under pi-hole.0.summary are updated
3. Wait some time or even a week
4. No values are updated anymore, stucks on values and date from adapter start

**Expected behavior**  
All values are updated continuously

**Versions:**  
 - Adapter version: 1.3.4
 - JS-Controller version: 4.0.23
 - Node version: v16.19.0
 - Operating system: docker image from: https://registry.hub.docker.com/r/buanet/iobroker/

**Comment by unltdnetworx** [comment]
Was steht denn in den Einstellungen des Adapters im Feld "Zeit in Sekunden, um neue Werte vom Pi-Hole-Gerät anzufordern."? Hier sollte eine Ganzzahl stehen. In diesem Zeitfenster werden die Werte dann neu von Pihole geholt.

**Comment by joerghohn** [comment]
Das wars, vielen Dank.
Da stand gar nichts drin, ich hatte nur die Zugangsdaten für den PiHole im Adapter eingetragen. Ein default Wert von 60 Sekunden oder so wäre da vielleicht nicht verkehrt.
