### ISSUE TITLE
npm ERR! notarget No matching version found for js-controller@>=2.0.0.

### ISSUE THREAD

**Issue by RP70DP** [unltdnetworx/ioBroker.pi-hole#46]
JS-Controller: 4.0.24

`$ iobroker upgrade pi-hole@1.3.5 --debug

Update pi-hole from @1.3.4 to @1.3.5

NPM version: 9.5.1

Installing iobroker.pi-hole@1.3.5... (System call)

npm ERR! notarget No matching version found for js-controller@>=2.0.0.

npm ERR! /opt/iobroker/.npm/_logs/2023-06-15T12_49_38_966Z-debug-0.log

upload [4] pi-hole.admin /opt/iobroker/node_modules/iobroker.pi-hole/admin/admin.d.ts admin.d.ts video/mp2t

upload [3] pi-hole.admin /opt/iobroker/node_modules/iobroker.pi-hole/admin/index_m.html index_m.html text/html

upload [2] pi-hole.admin /opt/iobroker/node_modules/iobroker.pi-hole/admin/pi-hole.png pi-hole.png image/png

upload [1] pi-hole.admin /opt/iobroker/node_modules/iobroker.pi-hole/admin/style.css style.css text/css

upload [0] pi-hole.admin /opt/iobroker/node_modules/iobroker.pi-hole/admin/words.js words.js application/javascript

Process exited with code 0`

**Comment by DschungelDaddy** [comment]
Auch dies kann ich bestätigen.
I can also confirm this.

**Comment by Azathoth88** [comment]
Same here.

**Comment by aklausing** [comment]
Same here.

**Comment by F3rd1Fuch5** [comment]
Got two different errors. First one was like the post #1. 
The second one was without further info. 
Im using JS controler 5.0.4

`$ iobroker upgrade pi-hole@1.3.5 --debug

Update pi-hole from @1.3.4 to @1.3.5

NPM version: 9.5.1

Installing iobroker.pi-hole@1.3.5... (System call)

npm ERR! code ETARGET

npm ERR! notarget No matching version found for js-controller@>=2.0.0.npm ERR! notarget In most cases you or one of your dependencies are requestingnpm ERR! notarget a package version that doesn't exist.npm ERR! A complete log of this run can be found in:npm ERR! /home/iobroker/.npm/_logs/2023-06-16T08_23_53_478Z-debug-0.log

upload [4] pi-hole.admin /opt/iobroker/node_modules/iobroker.pi-hole/admin/admin.d.ts admin.d.ts video/mp2t

upload [1] pi-hole.admin /opt/iobroker/node_modules/iobroker.pi-hole/admin/style.css style.css text/css

upload [0] pi-hole.admin /opt/iobroker/node_modules/iobroker.pi-hole/admin/words.js words.js application/javascript

Process exited with code 0`

First log
`0 verbose cli /usr/local/bin/node /usr/local/bin/npm
1 info using npm@9.5.1
2 info using node@v18.16.0
3 timing npm:load:whichnode Completed in 2ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 0ms
6 timing config:load:builtin Completed in 0ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/opt/iobroker/.npmrc Completed in 2ms
10 timing config:load:project Completed in 3ms
11 timing config:load:file:/home/iobroker/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 1ms
15 timing config:load:setEnvs Completed in 1ms
16 timing config:load Completed in 10ms
17 timing npm:load:configload Completed in 10ms
18 timing npm:load:mkdirpcache Completed in 0ms
19 timing npm:load:mkdirplogs Completed in 0ms
20 verbose title npm install iobroker.pi-hole@1.3.5
21 verbose argv "install" "--save-exact" "iobroker.pi-hole@1.3.5"
22 timing npm:load:setTitle Completed in 1ms
23 timing config:load:flatten Completed in 3ms
24 timing npm:load:display Completed in 4ms
25 verbose logfile logs-max:10 dir:/home/iobroker/.npm/_logs/2023-06-16T08_23_53_478Z-
26 verbose logfile /home/iobroker/.npm/_logs/2023-06-16T08_23_53_478Z-debug-0.log
27 timing npm:load:logFile Completed in 6ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 24ms
31 timing arborist:ctor Completed in 1ms
32 silly logfile start cleaning logs, removing 2 files
33 silly logfile done cleaning log files
34 timing idealTree:init Completed in 2133ms
35 timing idealTree:userRequests Completed in 14ms
36 silly idealTree buildDeps
37 silly fetch manifest iobroker.pi-hole@1.3.5
38 verbose shrinkwrap failed to load node_modules/.package-lock.json out of date, updated: node_modules/iobroker.alexa2
39 http fetch GET 200 https://registry.npmjs.org/iobroker.pi-hole 228ms (cache hit)
40 silly placeDep ROOT iobroker.pi-hole@1.3.5 REPLACE for: iobroker.inst@3.0.0 want: 1.3.5
41 silly fetch manifest js-controller@>=2.0.0
42 silly fetch manifest proxyquire@^2.1.3
43 http fetch GET 200 https://registry.npmjs.org/proxyquire 15ms (cache hit)
44 http fetch GET 200 https://registry.npmjs.org/js-controller 17ms (cache hit)
45 timing idealTree:#root Completed in 264ms
46 silly placeDep node_modules/iobroker.pi-hole js-controller@ OK for: iobroker.pi-hole@1.3.5 want: >=2.0.0
47 silly placeDep ROOT proxyquire@2.1.3 OK for: iobroker.pi-hole@1.3.5 want: ^2.1.3
48 silly fetch manifest fill-keys@^1.0.2
49 silly fetch manifest module-not-found-error@^1.0.1
50 http fetch GET 200 https://registry.npmjs.org/fill-keys 1326ms (cache hit)
51 http fetch GET 200 https://registry.npmjs.org/module-not-found-error 1327ms (cache hit)
52 timing idealTree:node_modules/iobroker.pi-hole Completed in 1333ms
53 silly placeDep ROOT fill-keys@1.0.2 OK for: proxyquire@2.1.3 want: ^1.0.2
54 silly placeDep ROOT module-not-found-error@1.0.1 OK for: proxyquire@2.1.3 want: ^1.0.1
55 silly fetch manifest is-object@~1.0.1
56 http fetch GET 200 https://registry.npmjs.org/is-object 738ms (cache hit)
57 timing idealTree:node_modules/proxyquire Completed in 745ms
58 silly placeDep ROOT is-object@1.0.2 OK for: fill-keys@1.0.2 want: ~1.0.1
59 timing idealTree:node_modules/fill-keys Completed in 4ms
60 timing idealTree:node_modules/is-object Completed in 0ms
61 timing idealTree:node_modules/module-not-found-error Completed in 0ms
62 timing idealTree:node_modules/iobroker.pi-hole/node_modules/js-controller Completed in 0ms
63 timing idealTree:buildDeps Completed in 2346ms
64 timing idealTree:fixDepFlags Completed in 24ms
65 timing idealTree Completed in 4539ms
66 timing command:install Completed in 4545ms
67 verbose type range
68 verbose stack js-controller: No matching version found for js-controller@>=2.0.0.
68 verbose stack     at module.exports (/usr/local/lib/node_modules/npm/node_modules/npm-pick-manifest/lib/index.js:209:23)
68 verbose stack     at RegistryFetcher.manifest (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/registry.js:119:22)
68 verbose stack     at async Promise.all (index 0)
68 verbose stack     at async [buildDepStep] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1044:5)
68 verbose stack     at async Arborist.buildIdealTree (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:207:7)
68 verbose stack     at async Promise.all (index 1)
68 verbose stack     at async Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:159:5)
68 verbose stack     at async Install.exec (/usr/local/lib/node_modules/npm/lib/commands/install.js:146:5)
68 verbose stack     at async module.exports (/usr/local/lib/node_modules/npm/lib/cli.js:134:5)
69 verbose cwd /opt/iobroker
70 verbose Linux 5.10.0-21-amd64
71 verbose node v18.16.0
72 verbose npm  v9.5.1
73 error code ETARGET
74 error notarget No matching version found for js-controller@>=2.0.0.
75 error notarget In most cases you or one of your dependencies are requesting
75 error notarget a package version that doesn't exist.
76 verbose exit 1
77 timing npm Completed in 4592ms
78 verbose unfinished npm timer reify 1686903833519
79 verbose unfinished npm timer reify:loadTrees 1686903833522
80 verbose code 1
81 error A complete log of this run can be found in:
81 error     /home/iobroker/.npm/_logs/2023-06-16T08_23_53_478Z-debug-0.log`

Seccond Error

`$ iobroker upgrade pi-hole@1.3.5 --debug

Update pi-hole from @1.3.4 to @1.3.5

NPM version: 9.5.1

Installing iobroker.pi-hole@1.3.5... (System call)

npm ERR! code ETARGET

npm ERR! A complete log of this run can be found in:npm ERR! /home/iobroker/.npm/_logs/2023-06-16T08_21_29_910Z-debug-0.log

upload [4] pi-hole.admin /opt/iobroker/node_modules/iobroker.pi-hole/admin/admin.d.ts admin.d.ts video/mp2t

upload [3] pi-hole.admin /opt/iobroker/node_modules/iobroker.pi-hole/admin/index_m.html index_m.html text/html

upload [2] pi-hole.admin /opt/iobroker/node_modules/iobroker.pi-hole/admin/pi-hole.png pi-hole.png image/png

upload [0] pi-hole.admin /opt/iobroker/node_modules/iobroker.pi-hole/admin/words.js words.js application/javascript

Process exited with code 0`

Second log
`0 verbose cli /usr/local/bin/node /usr/local/bin/npm
1 info using npm@9.5.1
2 info using node@v18.16.0
3 timing npm:load:whichnode Completed in 2ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/opt/iobroker/.npmrc Completed in 2ms
10 timing config:load:project Completed in 3ms
11 timing config:load:file:/home/iobroker/.npmrc Completed in 0ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 1ms
16 timing config:load Completed in 10ms
17 timing npm:load:configload Completed in 10ms
18 timing npm:load:mkdirpcache Completed in 0ms
19 timing npm:load:mkdirplogs Completed in 1ms
20 verbose title npm install iobroker.pi-hole@1.3.5
21 verbose argv "install" "--save-exact" "iobroker.pi-hole@1.3.5"
22 timing npm:load:setTitle Completed in 1ms
23 timing config:load:flatten Completed in 4ms
24 timing npm:load:display Completed in 5ms
25 verbose logfile logs-max:10 dir:/home/iobroker/.npm/_logs/2023-06-16T08_21_29_910Z-
26 verbose logfile /home/iobroker/.npm/_logs/2023-06-16T08_21_29_910Z-debug-0.log
27 timing npm:load:logFile Completed in 5ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 25ms
31 timing arborist:ctor Completed in 1ms
32 silly logfile start cleaning logs, removing 2 files
33 silly logfile done cleaning log files
34 timing idealTree:init Completed in 2309ms
35 timing idealTree:userRequests Completed in 14ms
36 silly idealTree buildDeps
37 silly fetch manifest iobroker.pi-hole@1.3.5
38 verbose shrinkwrap failed to load node_modules/.package-lock.json out of date, updated: node_modules/iobroker.alexa2
39 http fetch GET 200 https://registry.npmjs.org/iobroker.pi-hole 257ms (cache hit)
40 silly placeDep ROOT iobroker.pi-hole@1.3.5 REPLACE for: iobroker.inst@3.0.0 want: 1.3.5
41 silly fetch manifest js-controller@>=2.0.0
42 silly fetch manifest proxyquire@^2.1.3
43 http fetch GET 200 https://registry.npmjs.org/proxyquire 13ms (cache hit)
44 http fetch GET 200 https://registry.npmjs.org/js-controller 15ms (cache hit)
45 timing idealTree:#root Completed in 294ms
46 silly placeDep node_modules/iobroker.pi-hole js-controller@ OK for: iobroker.pi-hole@1.3.5 want: >=2.0.0
47 silly placeDep ROOT proxyquire@2.1.3 OK for: iobroker.pi-hole@1.3.5 want: ^2.1.3
48 silly fetch manifest fill-keys@^1.0.2
49 silly fetch manifest module-not-found-error@^1.0.1
50 http fetch GET 200 https://registry.npmjs.org/fill-keys 102ms (cache hit)
51 http fetch GET 200 https://registry.npmjs.org/module-not-found-error 103ms (cache hit)
52 timing idealTree:node_modules/iobroker.pi-hole Completed in 109ms
53 silly placeDep ROOT fill-keys@1.0.2 OK for: proxyquire@2.1.3 want: ^1.0.2
54 silly placeDep ROOT module-not-found-error@1.0.1 OK for: proxyquire@2.1.3 want: ^1.0.1
55 silly fetch manifest is-object@~1.0.1
56 http fetch GET 200 https://registry.npmjs.org/is-object 2052ms (cache hit)
57 timing idealTree:node_modules/proxyquire Completed in 2063ms
58 silly placeDep ROOT is-object@1.0.2 OK for: fill-keys@1.0.2 want: ~1.0.1
59 timing idealTree:node_modules/fill-keys Completed in 3ms
60 timing idealTree:node_modules/is-object Completed in 0ms
61 timing idealTree:node_modules/module-not-found-error Completed in 0ms
62 timing idealTree:node_modules/iobroker.pi-hole/node_modules/js-controller Completed in 0ms
63 timing idealTree:buildDeps Completed in 2472ms
64 timing idealTree:fixDepFlags Completed in 28ms
65 timing idealTree Completed in 4824ms
66 timing command:install Completed in 4831ms
67 verbose type range
68 verbose stack js-controller: No matching version found for js-controller@>=2.0.0.
68 verbose stack     at module.exports (/usr/local/lib/node_modules/npm/node_modules/npm-pick-manifest/lib/index.js:209:23)
68 verbose stack     at RegistryFetcher.manifest (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/registry.js:119:22)
68 verbose stack     at async Promise.all (index 0)
68 verbose stack     at async [buildDepStep] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1044:5)
68 verbose stack     at async Arborist.buildIdealTree (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:207:7)
68 verbose stack     at async Promise.all (index 1)
68 verbose stack     at async Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:159:5)
68 verbose stack     at async Install.exec (/usr/local/lib/node_modules/npm/lib/commands/install.js:146:5)
68 verbose stack     at async module.exports (/usr/local/lib/node_modules/npm/lib/cli.js:134:5)
69 verbose cwd /opt/iobroker
70 verbose Linux 5.10.0-21-amd64
71 verbose node v18.16.0
72 verbose npm  v9.5.1
73 error code ETARGET
74 error notarget No matching version found for js-controller@>=2.0.0.
75 error notarget In most cases you or one of your dependencies are requesting
75 error notarget a package version that doesn't exist.
76 verbose exit 1
77 timing npm Completed in 4877ms
78 verbose unfinished npm timer reify 1686903689951
79 verbose unfinished npm timer reify:loadTrees 1686903689954
80 verbose code 1
81 error A complete log of this run can be found in:
81 error     /home/iobroker/.npm/_logs/2023-06-16T08_21_29_910Z-debug-0.log`

**Comment by unltdnetworx** [comment]
Danke fürs Bescheid geben

**Comment by RP70DP** [comment]
v1.3.6 works. Thanks!

`$ iobroker upgrade pi-hole@1.3.6 --debug

Update pi-hole from @1.3.4 to @1.3.6

NPM version: 9.5.1

Installing iobroker.pi-hole@1.3.6... (System call)

added 4 packages, and changed 1 package in 17s185 packages are looking for funding run `npm fund` for details

Update "system.adapter.pi-hole.0"

upload [4] pi-hole.admin /opt/iobroker/node_modules/iobroker.pi-hole/admin/admin.d.ts admin.d.ts video/mp2t

upload [3] pi-hole.admin /opt/iobroker/node_modules/iobroker.pi-hole/admin/index_m.html index_m.html text/htmlupload [2] pi-hole.admin /opt/iobroker/node_modules/iobroker.pi-hole/admin/pi-hole.png pi-hole.png image/pngupload [1] pi-hole.admin /opt/iobroker/node_modules/iobroker.pi-hole/admin/style.css style.css text/cssupload [0] pi-hole.admin /opt/iobroker/node_modules/iobroker.pi-hole/admin/words.js words.js application/javascript

Process exited with code 0`
