### ISSUE TITLE
datenpunkt deklaration

### ISSUE THREAD

**Issue by liv-in-sky** [unltdnetworx/ioBroker.pi-hole#5]
hallo  - ich versuche gerade ein script zu schreiben, welches die datenpunkte etwas analysiert und auswertet - dabei ist aufgefallen , dass im adapter datenpunkte vom type text und value sind- man sagte mir, ich solle ein issue dazu erstellen
im forum: https://forum.iobroker.net/post/312375

es gibt so einen ähnlichen fall mit dem plex adapter: https://github.com/Zefau/ioBroker.plex/issues/15

hier mal ein kleine übersicht - es geht um die sollwerte - diese existieren in iobroker nicht

![Image 8](https://user-images.githubusercontent.com/18462890/67407945-8a9f6400-f5b8-11e9-8a9c-409fab81005e.png)

**Comment by unltdnetworx** [comment]
Sollte gefixed sein. Bitte überprüfen und schließen. Danke :)

**Comment by liv-in-sky** [comment]
danke  -alles gut
