### ISSUE TITLE
Slave Support

### ISSUE THREAD

**Issue by MarcoLaser** [unltdnetworx/ioBroker.pi-hole#6]
Fehler: "StartInstance system.adapter.pi-hole.0: required adapter "admin" not found!" Kommt auf Slave Systemen da dieser ja keinen eigenen Admin mehr hat.

**Comment by unltdnetworx** [comment]
Sollte behoben sein. Bitte schließen, wenn alles rund läuft.

**Comment by MarcoLaser** [comment]
Wow das war mal schnell!
Klappt alles, besten Dank
